// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_HeartRateImage;
lv_obj_t * ui_HeartRate;
lv_obj_t * ui_BloodOxygenImage;
lv_obj_t * ui_BloodOxygen;
lv_obj_t * ui_BodyTempImage;
lv_obj_t * ui_BodyTemp;
lv_obj_t * ui_Time;
lv_obj_t * ui_TimeSeconds;
lv_obj_t * ui_Bar1;
lv_obj_t * ui_Power;
lv_obj_t * ui_ChargingImage;
lv_obj_t * ui_UVRaysImage;
lv_obj_t * ui_WeatherPlaceholder;
lv_obj_t * ui_UVRays;
lv_obj_t * ui_AtmosphereImage;
lv_obj_t * ui_Atmosphere;
lv_obj_t * ui_Compass;
lv_obj_t * ui_DistanceImage;
lv_obj_t * ui_StepsImage;
lv_obj_t * ui_Steps;
lv_obj_t * ui_Distance;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
