// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_HeartRateImage;
extern lv_obj_t * ui_HeartRate;
extern lv_obj_t * ui_BloodOxygenImage;
extern lv_obj_t * ui_BloodOxygen;
extern lv_obj_t * ui_BodyTempImage;
extern lv_obj_t * ui_BodyTemp;
extern lv_obj_t * ui_Time;
extern lv_obj_t * ui_TimeSeconds;
extern lv_obj_t * ui_Bar1;
extern lv_obj_t * ui_Power;
extern lv_obj_t * ui_ChargingImage;
extern lv_obj_t * ui_UVRaysImage;
extern lv_obj_t * ui_WeatherPlaceholder;
extern lv_obj_t * ui_UVRays;
extern lv_obj_t * ui_AtmosphereImage;
extern lv_obj_t * ui_Atmosphere;
extern lv_obj_t * ui_Compass;
extern lv_obj_t * ui_DistanceImage;
extern lv_obj_t * ui_StepsImage;
extern lv_obj_t * ui_Steps;
extern lv_obj_t * ui_Distance;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_heartbeat_png);    // assets/heartbeat.png
LV_IMG_DECLARE(ui_img_drop_png);    // assets/drop.png
LV_IMG_DECLARE(ui_img_thermometer_png);    // assets/thermometer.png
LV_IMG_DECLARE(ui_img_lightning_png);    // assets/lightning.png
LV_IMG_DECLARE(ui_img_sunglasses_png);    // assets/sunglasses.png
LV_IMG_DECLARE(ui_img_1407854121);    // assets/cloud-sun.png
LV_IMG_DECLARE(ui_img_2104800269);    // assets/cloud-fog.png
LV_IMG_DECLARE(ui_img_ruler_png);    // assets/ruler.png
LV_IMG_DECLARE(ui_img_960456026);    // assets/sneaker-move.png

// FONTS
LV_FONT_DECLARE(ui_font_Roboto);
LV_FONT_DECLARE(ui_font_RobotoBIG);
LV_FONT_DECLARE(ui_font_RobotoMedium);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
